FROM python:3.11

WORKDIR /flask-app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . /flask-app

EXPOSE 5000


CMD ["python", "/flask-app/app.py", "--host", "0.0.0.0", "--port", "5000"]
